FSDP_PrefFut/FSDP_PrefFut/Controllers/LocationsController.cs
using System;
using System.Collections.Generic;
using Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Domain;//added ctrl. on unitofwork
using Microsoft.AspNet.Identity;//added for identity

namespace FSDP_PrefFut.Controllers
{
[Authorize]
    public class LocationsController : Controller
    {
        //UnitOfWork uow = new UnitOfWork();
        PreferredFuturesEntities db = new PreferredFuturesEntities();

        string title = "Classes & Locations";

        [AllowAnonymous]
        public ActionResult Index()
        {
			ViewBag.Title = title;

            ////to display name instead of GUID
            //List<UserDetail> deets = db.UserDetails.ToList();
            //ViewBag.userDeets = deets;


            //GET: Locations ...... 
            var locations = db.Locations.ToList();
            return View(locations.ToList());
        }

        [Authorize(Roles = "Admin, Teacher")]
        public ActionResult Create()
        {
            ////to display name instead of GUID
            //List<UserDetail> deets = db.UserDetails.ToList();
            //ViewBag.userDeets = deets;

            ViewBag.Title = title;
            ViewBag.LocationID = new SelectList(db.Locations.ToList(), "LocationID", "LocationName");
            ViewBag.StudentDocID = new SelectList(db.StudentDocs, "StudentDocID", "DocName");
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin, Teacher")]
        public ActionResult Create([Bind(Include = "LocationID,LocationName,Address,City,State,ZipCode,ReservationLimit,TeacherID,DocRequirements,Comments")] Location location)
        {
			ViewBag.Title = title;

            var teacherID = User.Identity.GetUserId();
            var userFirstName = User.Identity.GetUserId();

            if (ModelState.IsValid)
            {
                location.TeacherID = userFirstName;

                db.Locations.Add(location);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(location);
        }

        [Authorize(Roles = "Admin, Teacher")]
        public ActionResult Edit(int? id)
        {
            ////to display name instead of GUID
            //List<UserDetail> deets = db.UserDetails.ToList();
            //ViewBag.userDeets = deets;


            ViewBag.Title = title;
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Location location = db.Locations.Find(id);
            if (location == null)
            {
                return HttpNotFound();
            }
            return View(location);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin, Teacher")]
        public ActionResult Edit([Bind(Include = "LocationID,LocationName,Address,City,State,ZipCode,ReservationLimit,TeacherID,DocRequirements,Comments")] Location location)
        {
			ViewBag.Title = title;
            if (ModelState.IsValid)
            {
                db.Entry(location).State = EntityState.Modified; ;
                db.SaveChanges();

                return RedirectToAction("Index");
            }
            return View(location);
        }

        [Authorize(Roles = "Admin")]
        public ActionResult Delete(int id)
        {
			ViewBag.Title = title;
            Location location = db.Locations.Find(id);
            db.Locations.Remove(location);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

FSDP_PrefFut/FSDP_PrefFut/Controllers/ReservationsController.cs
using System;
using System.Collections.Generic;
using Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Domain;//added ctrl. on unitofwork
using Microsoft.AspNet.Identity;//added for identity
//using System.Data.Entity;//added for enttities

namespace FSDP_PrefFut.Controllers
{
    [Authorize(Roles = "Admin, Teacher, Student")]
    public class ReservationsController : Controller
    {
        //UnitOfWork uow = new UnitOfWork();

        PreferredFuturesEntities db = new PreferredFuturesEntities();
        string title = "Class Reservation";

        public ActionResult Index()
        {
            //to display name instead of GUID
            List<UserDetail> deets = db.UserDetails.ToList();
            ViewBag.userDeets = deets;

            ViewBag.Title = title;
            //var reservations = new List<Data.Reseration>();
            //var studentDocID = db.StudentDocs.ToList();
            var reservations = db.Reservations.ToList();
            var userId = User.Identity.GetUserId();
            var studentDoc = db.StudentDocs.Where(s => s.StudentID == userId);

            //var res = db.Reservations.Where(rd => rd.ReservationDate == reservation.ReservationDate && rd.LocationID == reservation.LocationID).Single();
            //var studentID = db.Reservations.Where(s => s.StudentDocID == db.StudentDocs.StudentDocID && s.StudentDoc == studentDoc.StudentID).Single();

            //var studentID = db.StudentDocs.ToList().Where(s => s.StudentID == userId).ToList();
            if (User.IsInRole("Admin"))
            {
                reservations = db.Reservations.ToList();
            }
            else
                        if (User.IsInRole("Teacher"))
            {
                reservations = db.Reservations.ToList();
            }
            else
            {
                List<Reservation> stuRes = new List<Reservation>();
                var SDID = db.StudentDocs.Where(x => x.StudentID == userId);
                foreach (var r in db.Reservations)
                {
                    foreach (var s in SDID)
                    {
                        if (r.StudentDocID == s.StudentDocID)
                        {
                            stuRes.Add(r);
                        }
                    }
                }
                return View(stuRes.ToList());
                //var userId = User.Identity.GetUserId();
                //reservations = db.Reservations.ToList().Where(s => s.StudentID == userId).ToList();
                //reservations = db.Reservations.ToList().Where(s.studentID == userId);
            }
            return View(reservations.ToList());
        }


        public ActionResult Create()
        {
			ViewBag.Title = title;
            var userId = User.Identity.GetUserId();
            var studentDoc = db.StudentDocs.Where(s => s.StudentID == userId);
            string currentUserID = User.Identity.GetUserId();
            //ViewBag.TeacherID = new SelectList(db.Locations.Where(tID => tID.UserID == ))
            ViewBag.LocationID = new SelectList(db.Locations.ToList(), "LocationID", "LocationName");
            ViewBag.StudentDocID = new SelectList(db.StudentDocs.Where(s => s.StudentID == userId), "StudentDocID", "DocName");
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ReservationID,LocationID,ReservationDate,TeacherID,StudentDocID")] Reservation reservation)
        {
			ViewBag.Title = title;
            ////to display name instead of GUID
            //List<UserDetail> deets = db.UserDetails.ToList();
            //ViewBag.userDeets = deets;

            if (ModelState.IsValid)
            {
                //Location location = db.Locations.Where(l => l.LocationID == reservation.LocationID).Single();
                var res = db.Reservations.Where(rd => rd.ReservationDate == reservation.ReservationDate && rd.LocationID == reservation.LocationID).SingleOrDefault();
                //if (location.ReservationLimit <= location.ReservationLimit)
                if (res == null)
                {
                    db.Reservations.Add(reservation);
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
                ViewBag.ErrorMessage = "The class size limit has been reached.  Please select a different date.";

                //db.Reservations.Add(reservation);
                //db.SaveChanges();
            }

            ViewBag.LocationID = new SelectList(db.Locations.ToList(), "LocationID", "LocationName");
            ViewBag.StudentDocID = new SelectList(db.StudentDocs.ToList(), "StudentDocID", "DocName");
            return View(reservation);
        }

        [Authorize(Roles = "Admin, Teacher")]
        public ActionResult Edit(int? id)
        {
            ////to display name instead of GUID
            //List<UserDetail> deets = db.UserDetails.ToList();
            //ViewBag.userDeets = deets;

            ViewBag.Title = title;
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Reservation reservation = db.Reservations.Find(id);
            if (reservation == null)
            {
                return HttpNotFound();
            }
            ViewBag.LocationID = new SelectList(db.Locations.ToList(), "LocationID", "LocationName");
            ViewBag.StudentDocID = new SelectList(db.StudentDocs.ToList(), "StudentDocID", "DocName");
            return View(reservation);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin, Teacher")]
        public ActionResult Edit([Bind(Include = "ReservationID,LocationID,ReservationDate,TeacherID,StudentDocID")] Reservation reservation)
        {

            ////to display name instead of GUID
            //List<UserDetail> deets = db.UserDetails.ToList();
            //ViewBag.userDeets = deets;

            ViewBag.Title = title;
            var userId = User.Identity.GetUserId();
            if (ModelState.IsValid)
            {
                reservation.TeacherID = userId;

                db.Entry(reservation).State = EntityState.Modified; ;
                db.SaveChanges();

                return RedirectToAction("Index");
            }
            ViewBag.LocationID = new SelectList(db.Locations.ToList(), "LocationID", "LocationName");
            ViewBag.StudentDocID = new SelectList(db.StudentDocs.ToList(), "StudentDocs", "DocName");
            return View(reservation);
        }

        [Authorize(Roles = "Admin, Teacher")]
        public ActionResult Delete(int id)
        {
			ViewBag.Title = title;
            Reservation reservation = db.Reservations.Find(id);
            db.Reservations.Remove(reservation);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

FSDP_PrefFut/FSDP_PrefFut/Controllers/StudentDocsController.cs
using System;
using System.Collections.Generic;
using Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Domain;//added ctrl. on unitofwork
using Microsoft.AspNet.Identity;//added for identity
using System.IO;//added for image 
using System.Drawing;//added for image 
using Utilities;//added for image 


namespace FSDP_PrefFut.Controllers
{
    [Authorize]
    public class StudentDocsController : Controller
    {
        //UnitOfWork uow = new UnitOfWork();
        PreferredFuturesEntities db = new PreferredFuturesEntities();
        string title = "Student Documents";

        public ActionResult Index()
        {
            //to display name instead of GUID
            List<UserDetail> deets = db.UserDetails.ToList();
            ViewBag.userDeets = deets;


            ViewBag.Title = title;
            var studentDocs = new List<Data.StudentDoc>();
            if (User.IsInRole("Admin"))
            {
                studentDocs = db.StudentDocs.ToList().ToList();
            }
            else
            {
                var userId = User.Identity.GetUserId();
                studentDocs = db.StudentDocs.ToList().Where(s => s.StudentID == userId).ToList();
            }
            return View(studentDocs);
        }

        public ActionResult Create()
        {
			ViewBag.Title = title;
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "StudentDocID,DocName,StudentID,StudentPhoto,SpecialNotes,IsActive,DateAdded")] StudentDoc studentDoc, HttpPostedFileBase edlFileUpload, HttpPostedFileBase userImageUpload)
        {
			ViewBag.Title = title;

            ////to display name instead of GUID
            //List<UserDetail> deets = db.UserDetails.ToList();
            //ViewBag.userDeets = deets;

            //file and image upload
            FileUtilities.UploadFile(Server.MapPath("~/Content/images/"), edlFileUpload.FileName, edlFileUpload);

            FileUtilities.UploadFile(Server.MapPath("~/Content/images/"), userImageUpload.FileName, userImageUpload);
            //var edlFileUpload = FileUtilities.UploadFile(studentDoc.DocName);
            //var userImageUpload = ImageUtilities.ResizeImage(studentDoc.StudentPhoto);

            var dateAdded = DateTime.Now;
            var dateOnlyString = dateAdded.ToShortDateString();
            var userId = User.Identity.GetUserId();
            var studentName = db.StudentDocs.ToList();
            

            if (ModelState.IsValid)
            {

                studentDoc.DocName = edlFileUpload.FileName;
                studentDoc.StudentPhoto = userImageUpload.FileName;
                studentDoc.StudentID = userId;
                studentDoc.DateAdded = dateAdded;

                db.StudentDocs.Add(studentDoc);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(studentDoc);
        }

        public ActionResult Edit(int? id)
        {
            ////to display name instead of GUID
            //List<UserDetail> deets = db.UserDetails.ToList();
            //ViewBag.userDeets = deets;

            ViewBag.Title = title;
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            StudentDoc studentDoc = db.StudentDocs.Find(id);
            if (studentDoc == null)
            {
                return HttpNotFound();
            }
            return View(studentDoc);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "StudentDocID,DocName,StudentID,StudentPhoto,SpecialNotes,IsActive,DateAdded")] StudentDoc studentDoc, HttpPostedFileBase edlFileUpload, HttpPostedFileBase userImageUpload)
        {

            ////to display name instead of GUID
            //List<UserDetail> deets = db.UserDetails.ToList();
            //ViewBag.userDeets = deets;


            ViewBag.Title = title;
            //file and image upload

            FileUtilities.UploadFile(Server.MapPath("~/Content/images/"), edlFileUpload.FileName, edlFileUpload);
            FileUtilities.UploadFile(Server.MapPath("~/Content/images/"), userImageUpload.FileName, userImageUpload);
            //var edlFileUpload = FileUtilities.UploadFile(studentDoc.DocName);
            //var userImageUpload = ImageUtilities.ResizeImage(studentDoc.StudentPhoto);

            var dateAdded = DateTime.Now;
            var dateOnlyString = dateAdded.ToShortDateString();
            var userId = User.Identity.GetUserId();

            if (ModelState.IsValid)
            {

                studentDoc.DocName = edlFileUpload.FileName;
                studentDoc.StudentPhoto = userImageUpload.FileName;
                studentDoc.StudentID = userId;
                studentDoc.DateAdded = dateAdded;

                db.Entry(studentDoc).State = EntityState.Modified; ;
                db.SaveChanges();

                return RedirectToAction("Index");
            }
            return View(studentDoc);
        }

        //[Authorize(Roles = "Admin")]
        public ActionResult Delete(int id)
        {
			ViewBag.Title = title;
            StudentDoc studentDoc = db.StudentDocs.Find(id);
            db.StudentDocs.Remove(studentDoc);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

FSDP_PrefFut/FSDP_PrefFut/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>@ViewBag.Title - Preferred Futures</title>

    <!-- Bootstrap core CSS -->
    <link href="~/Content/styles/css/bootstrap.min.css" rel="stylesheet" />
    @*<link href="~/Content/styles/bootstrap/css/bootstrap.min.css" rel="stylesheet">*@
    @*<link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet" />*@

    <!-- Custom styles for this template -->
    <link href="~/Content/css/full-width-pics.css" rel="stylesheet">
    @*<link href="https://code.jquery.com/ui/1.12.1/themes/ui-lightness/jquery-ui.css" rel="stylesheet" />*@
    <link href="~/Content/Styles/Site.css" rel="stylesheet" />


    @*PrefFut favicon*@
    <link rel="apple-touch-icon" sizes="57x57" href="/apple-icon-57x57.png">
    <link rel="apple-touch-icon" sizes="60x60" href="/apple-icon-60x60.png">
    <link rel="apple-touch-icon" sizes="72x72" href="/apple-icon-72x72.png">
    <link rel="apple-touch-icon" sizes="76x76" href="/apple-icon-76x76.png">
    <link rel="apple-touch-icon" sizes="114x114" href="/apple-icon-114x114.png">
    <link rel="apple-touch-icon" sizes="120x120" href="/apple-icon-120x120.png">
    <link rel="apple-touch-icon" sizes="144x144" href="/apple-icon-144x144.png">
    <link rel="apple-touch-icon" sizes="152x152" href="/apple-icon-152x152.png">
    <link rel="apple-touch-icon" sizes="180x180" href="/apple-icon-180x180.png">
    <link rel="icon" type="image/png" sizes="192x192" href="/android-icon-192x192.png">
    <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="96x96" href="/favicon-96x96.png">
    <link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png">
    <link rel="manifest" href="/manifest.json">
    <meta name="msapplication-TileColor" content="#ffffff">
    <meta name="msapplication-TileImage" content="/ms-icon-144x144.png">
    <meta name="theme-color" content="#ffffff">

    @RenderSection("styles", required: false)

</head>
<body>
    <!-- Navigation -->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top" style="color:darkgrey" display="block">
        <div class="container">

            <a class="navbar-brand" href="@Url.Action("Index", "Home")"><img class="img-fluid d-block mx-auto" src="~/Content/images/pfSwirl.jpg" style="max-height: 50px; max-width: 50px"alt="Logo"></a>
            <a class="navbar-brand" href="@Url.Action("Index", "Home")">Preferred Futures</a>


            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarResponsive">
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item active">

                        <a class="nav-link" href="@Url.Action("Index", "Home")">
                            Home
                            <span class="sr-only">(current)</span>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="@Url.Action("About", "Home")">About</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="@Url.Action("Contact", "Home")">Contact</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="@Url.Action("Index","Locations")">Training Locations</a>
                    </li>

                    @if (User.IsInRole("Student"))
                    {
                        <li class="nav-item">
                            <a class="nav-link" href="@Url.Action("Index", "StudentDocs")">Student Docs</a>
                        </li>
                                <li class="nav-item">
                                    <a class="nav-link" href="@Url.Action("Index", "Reservations")">Reservations</a>
                                </li>

                    }

                    @*<li class="nav-item">
                                                <a class="nav-link" href="@Url.Action("Index","StudentDocs")">Student Docs</a>
                                            </li>
                        <li class="nav-item">
                            <a class="nav-link" href="@Url.Action("Index","Reservations")">Reservations</a>
                        </li>*@

                    @*@if (User.IsInRole("Admin") || User.IsInRole("Student"))*@
@if (User.IsInRole("Admin"))

{
                        <li class="nav-item">
                            <a class="nav-link" href="@Url.Action("Index", "StudentDocs")">Student Docs</a>
                        </li>
                                    <li class="nav-item">
                                        <a class="nav-link" href="@Url.Action("Index", "Reservations")">Reservations</a>
                                    </li>
                    }


                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </nav>
    <!-- Header - set the background image for the header in the line below -->
    <header class="py-5 bg-image-full" style="background-image: url('../../Content/images/hands01.jpg'); ">
        <div style="height: 200px;"></div>
    </header>
    <div class="container body-content">
        <div id="MessageDisplay" class="md-col-10 md-col-offset-1">
            @if (ViewBag.MessageDisplay != null)
            {
                <div id="MessageBanner" class="alert alert-warning">
                    @ViewBag.MessageDisplay
                </div>
            }
        </div>

        @RenderBody()

        <hr />

        <!-- Footer -->
        <footer class="py-5 bg-dark" style="max-height: 100px; max-width: 992px">
            <div class="container">
                <p class="m-0 text-center text-white">
                    Copyright &copy; Preferred Futures, Inc. @DateTime.Now.Year    |    Template Design by
                    <a href="https://startbootstrap.com/" target="blank">Start Bootstrap</a>
            </div></p>
            <!-- /.container -->
        </footer>
    </div>

    @*<script src="Conetnt/scripts/jquery/jquery.min.js"></script>*@
    @*<script src="Content/styles/js/bootstrap.bundle.min.js"></script>*@

    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    @*<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>*@
    <script src="~/Content/scripts/bootstrap.bundle.js"></script>
    <script src="https://code.jquery.com/ui/1.12.0/jquery-ui.min.js"></script>

    @RenderSection("scripts", required: false)
</body>
</html>