FSDP_PrefFut/FSDP_PrefFut/_archive/Controllers/StudentDocsController.cs
using System;
using System.Collections.Generic;
using Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Domain;//added ctrl. on unitofwork
using Microsoft.AspNet.Identity;//added for identity
using System.IO;//added for image 
using System.Drawing;//added for image 
using Utilities;//added for image 


namespace FSDP_PrefFut.Controllers
{
    [Authorize]
    public class StudentDocsController : Controller
    {
        //UnitOfWork uow = new UnitOfWork();
        PreferredFuturesEntities db = new PreferredFuturesEntities();
        string title = "Student Documents";

        public ActionResult Index()
        {
            //to display name instead of GUID
            List<UserDetail> deets = db.UserDetails.ToList();
            ViewBag.userDeets = deets;


            ViewBag.Title = title;
            var studentDocs = new List<Data.StudentDoc>();
            if (User.IsInRole("Admin"))
            {
                studentDocs = db.StudentDocs.ToList().ToList();
            }
            else
            {
                var userId = User.Identity.GetUserId();
                studentDocs = db.StudentDocs.ToList().Where(s => s.StudentID == userId).ToList();
            }
            return View(studentDocs);
        }

        public ActionResult Create()
        {
			ViewBag.Title = title;
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "StudentDocID,DocName,StudentID,StudentPhoto,SpecialNotes,IsActive,DateAdded")] StudentDoc studentDoc, HttpPostedFileBase edlFileUpload, HttpPostedFileBase userImageUpload)
        {
			ViewBag.Title = title;

            ////to display name instead of GUID
            //List<UserDetail> deets = db.UserDetails.ToList();
            //ViewBag.userDeets = deets;

            //file and image upload
            FileUtilities.UploadFile(Server.MapPath("~/Content/images/"), edlFileUpload.FileName, edlFileUpload);

            FileUtilities.UploadFile(Server.MapPath("~/Content/images/"), userImageUpload.FileName, userImageUpload);
            //var edlFileUpload = FileUtilities.UploadFile(studentDoc.DocName);
            //var userImageUpload = ImageUtilities.ResizeImage(studentDoc.StudentPhoto);

            var dateAdded = DateTime.Now;
            var dateOnlyString = dateAdded.ToShortDateString();
            var userId = User.Identity.GetUserId();
            var studentName = db.StudentDocs.ToList();
            

            if (ModelState.IsValid)
            {

                studentDoc.DocName = edlFileUpload.FileName;
                studentDoc.StudentPhoto = userImageUpload.FileName;
                studentDoc.StudentID = userId;
                studentDoc.DateAdded = dateAdded;

                db.StudentDocs.Add(studentDoc);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(studentDoc);
        }

        public ActionResult Edit(int? id)
        {
            ////to display name instead of GUID
            //List<UserDetail> deets = db.UserDetails.ToList();
            //ViewBag.userDeets = deets;

            ViewBag.Title = title;
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            StudentDoc studentDoc = db.StudentDocs.Find(id);
            if (studentDoc == null)
            {
                return HttpNotFound();
            }
            return View(studentDoc);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "StudentDocID,DocName,StudentID,StudentPhoto,SpecialNotes,IsActive,DateAdded")] StudentDoc studentDoc, HttpPostedFileBase edlFileUpload, HttpPostedFileBase userImageUpload)
        {

            ////to display name instead of GUID
            //List<UserDetail> deets = db.UserDetails.ToList();
            //ViewBag.userDeets = deets;


            ViewBag.Title = title;
            //file and image upload

            FileUtilities.UploadFile(Server.MapPath("~/Content/images/"), edlFileUpload.FileName, edlFileUpload);
            FileUtilities.UploadFile(Server.MapPath("~/Content/images/"), userImageUpload.FileName, userImageUpload);
            //var edlFileUpload = FileUtilities.UploadFile(studentDoc.DocName);
            //var userImageUpload = ImageUtilities.ResizeImage(studentDoc.StudentPhoto);

            var dateAdded = DateTime.Now;
            var dateOnlyString = dateAdded.ToShortDateString();
            var userId = User.Identity.GetUserId();

            if (ModelState.IsValid)
            {

                studentDoc.DocName = edlFileUpload.FileName;
                studentDoc.StudentPhoto = userImageUpload.FileName;
                studentDoc.StudentID = userId;
                studentDoc.DateAdded = dateAdded;

                db.Entry(studentDoc).State = EntityState.Modified; ;
                db.SaveChanges();

                return RedirectToAction("Index");
            }
            return View(studentDoc);
        }

        [Authorize(Roles = "Admin")]
        public ActionResult Delete(int id)
        {
			ViewBag.Title = title;
            StudentDoc studentDoc = db.StudentDocs.Find(id);
            db.StudentDocs.Remove(studentDoc);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

FSDP_PrefFut/FSDP_PrefFut/_archive/Views/StudentDocs/Create.cshtml
@model Data.StudentDoc
@using Data

@{
}

@*<h2>Create @ViewBag.Title</h2>*@
<section class="py-5">
    <div class="container">
        <h1>Create @ViewBag.Title</h1>


        @using (Html.BeginForm("Create", "StudentDocs", FormMethod.Post, new { enctype = "multipart/form-data" }))
        {
            @Html.AntiForgeryToken()

            <div class="form-horizontal">
                <hr />
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                <div class="form-group">
                    @Html.LabelFor(model => model.DocName, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @*@Html.EditorFor(model => model.DocName, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.DocName, "", new { @class = "text-danger" })*@
                        <input type="file" name="edlFileUpload" />

                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.StudentID, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @*@Html.EditorFor(model => model.StudentID, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.StudentID, "", new { @class = "text-danger" })*@

                        @*var userId = User.Identity.GetUserId();*@
                        @User.Identity.Name

                        @*studentDocs = uow.StudentDocRepository.Get().Where(s => s.StudentID == userId).ToList();*@
                        @*@foreach (UserDetail user in ViewBag.userDeets)
                        {
                            if (item.StudentID == user.UserID)
                            {
                                <p>@user.FirstName @user.LastName</p>
                            }
                        }*@

                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.StudentPhoto, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @*@Html.EditorFor(model => model.StudentPhoto, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.StudentPhoto, "", new { @class = "text-danger" })*@
                        <input type="file" name="userImageUpload" />

                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.SpecialNotes, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.SpecialNotes, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.SpecialNotes, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.IsActive, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        <div class="checkbox">
                            @Html.EditorFor(model => model.IsActive)
                            @Html.ValidationMessageFor(model => model.IsActive, "", new { @class = "text-danger" })
                        </div>
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.DateAdded, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @*@Html.EditorFor(model => model.DateAdded, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.DateAdded, "", new { @class = "text-danger" })*@
                        @*<input type="date" />------------ this adds a calendar to pick the date *@
                        @DateTime.Now

                    </div>
                </div>

                <div class="form-group">
                    <div class="row">
                        <div class="col-md-9">
                            <input type="submit" value="Create" class="btn btn-success" />
                        </div>
                        <div class="col-md-1">
                            <a href="@Url.Action("Index")" class="btn btn-info">Back To List</a>
                        </div>
                    </div>
                </div>
            </div>
        }
    </div>

    @section Scripts {
        @Scripts.Render("~/bundles/jqueryval")
    }
</section>

FSDP_PrefFut/FSDP_PrefFut/_archive/Views/StudentDocs/Delete.cshtml
@model Data.StudentDoc

@{
    ViewBag.Title = "Delete";
}

<section class="py-5">
    <div class="container">
        <h1>Delete</h1>

        @*<h2>Delete</h2>*@

        <h3>Are you sure you want to delete this?</h3>
        <div>
            <h4>Student Documents</h4>
            <hr />
            <dl class="dl-horizontal">
                <dt>
                    @Html.DisplayNameFor(model => model.DocName)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.DocName)
                </dd>

                @*<dt>
                        @Html.DisplayNameFor(model => model.StudentID)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.StudentID)
                    </dd>*@

                <dt>
                    @Html.DisplayNameFor(model => model.StudentPhoto)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.StudentPhoto)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.SpecialNotes)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.SpecialNotes)
                </dd>

                @*<dt>
                        @Html.DisplayNameFor(model => model.IsActive)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.IsActive)
                    </dd>

                    <dt>
                        @Html.DisplayNameFor(model => model.DateAdded)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.DateAdded)
                    </dd>*@

            </dl>

            @using (Html.BeginForm())
            {
                @Html.AntiForgeryToken()
                <div class="form-actions no-color">
                    <input type="submit" value="Delete" class="btn btn-default" /> |
                    @Html.ActionLink("Back to List", "Index")
                </div>
            }
        </div>
    </div>
    </section>

FSDP_PrefFut/FSDP_PrefFut/_archive/Views/StudentDocs/Details.cshtml
@model Data.StudentDoc
@using Data


@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Student Document Details</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.DocName)
        </dt>

        <dd>
            @*@Html.DisplayFor(model => model.DocName)*@
            <img src="~/Content/images/" + model.DocName alt="model.DocName" title="EDL" />
        </dd>

        <dt>
        @Html.HiddenFor(model => model.StudentID)
    </dt>

        <dd>
            @*@foreach (UserDetail user in ViewBag.userDeets)
            {
                if (item.StudentID == user.UserID)
                {
                    <p>@user.FirstName @user.LastName</p>
                }
            }*@

            @Html.DisplayFor(model => model.StudentID)
            @*@User.Identity.Name*@
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.StudentPhoto)
        </dt>

        <dd>
            @*@Html.DisplayFor(model => model.StudentPhoto)*@
            @*<img src="~/Content/images/" alt="" title="Photo" />*@
            <img src="~/Content/images/" + model.StudentPhoto)" alt=Model.StudentPhoto title="Photo" />
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SpecialNotes)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SpecialNotes)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.IsActive)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IsActive)
            @*@Html.YesNo(ITempDataProvider.IsTrue)*@
        </dd>

        @*<dt>
            @Html.DisplayNameFor(model => model.DateAdded)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DateAdded)
        </dd>*@

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.StudentDocID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

FSDP_PrefFut/FSDP_PrefFut/_archive/Views/StudentDocs/Edit.cshtml
@model Data.StudentDoc
    @using Data

@{
}

@section styles {
    <style>
        .control-label {
            font-weight: bold;
            color: black;
        }

        input.detailDisplay {
            background-color: white !important;
            box-shadow: none;
            border: 0;
            color: black;
        }

        .editForm input, .editForm select {
            color: black;
            background-color: rgba(255, 216, 0, .3);
        }
    </style>}

<section class="py-5">
    <div class="container">
        <h1>@ViewBag.Title</h1>

        @using (Html.BeginForm("Edit", "StudentDocs", FormMethod.Post, new { enctype = "multipart/form-data" }))
        {
            @Html.AntiForgeryToken()

            <div class="form-horizontal">
                @*<h4>Edit Student Document Information</h4>*@
                <h2><span class="editForm">Edit </span>@*@ViewBag.Title*@<span class="detailDisplay"> Details</span></h2>
                <hr />

                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                @Html.HiddenFor(model => model.StudentDocID)

                @*FILE UPLOAD (edit-only) track orignal image filename*@
                @Html.HiddenFor(model => model.DocName)
                @Html.HiddenFor(model => model.StudentPhoto)

                <div class="form-group">

                    @Html.LabelFor(model => model.DocName, htmlAttributes: new { @class = "control-label col-md-2" })

                    <div class="col-md-10">
                        @* FILE UPLOAD - replace textbox w/ file upload control *@
                        @*<input type="text" name="roDocName" value="@Model.DocName" class="detailDisplay form-control" readonly />
                            <div class="editForm">
                            @Html.EditorFor(model => model.DocName, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.DocName, "", new { @class = "text-danger" })*@
                        <input type="file" name="edlFileUpload" alt="item.DocName" />

                    </div>
                </div>
            </div>
            @*<div class="form-group">

                @Html.LabelFor(model => model.StudentID, htmlAttributes: new { @class = "control-label col-md-2" })

                <div class="col-md-10">
                    <input type="text" name="roStudentID" value="@Model.StudentID" class="detailDisplay form-control" readonly />
                    <div class="editForm">
                        @Html.EditorFor(model => model.StudentID, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.StudentID, "", new { @class = "text-danger" })
                        @User.Identity.Name
                        @foreach (UserDetail user in ViewBag.userDeets)
                        {
                            if (item.StudentID == user.UserID)
                            {
                                <p>@user.FirstName @user.LastName</p>
                            }
                        }
                    </div>
                </div>
            </div>*@
            <div class="form-group">

                @Html.LabelFor(model => model.StudentPhoto, htmlAttributes: new { @class = "control-label col-md-2" })

                <div class="col-md-10">
                    <input type="text" name="roStudentPhoto" value="@Model.StudentPhoto" class="detailDisplay form-control" readonly />
                    <div class="editForm">
                        @* FILE UPLOAD - replace textbox w/ file upload control *@
                        @*@Html.EditorFor(model => model.StudentPhoto, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.StudentPhoto, "", new { @class = "text-danger" })*@
                        <input type="file" name="userImageUpload" />
                    </div>
                </div>
            </div>
            <div class="form-group">

                @Html.LabelFor(model => model.SpecialNotes, htmlAttributes: new { @class = "control-label col-md-2" })

                <div class="col-md-10">
                    <input type="text" name="roSpecialNotes" value="@Model.SpecialNotes" class="detailDisplay form-control" readonly />
                    <div class="editForm">
                        @Html.EditorFor(model => model.SpecialNotes, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.SpecialNotes, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>
            <div class="form-group">

                @Html.LabelFor(model => model.IsActive, htmlAttributes: new { @class = "control-label col-md-2" })

                <div class="col-md-10">
                    <input type="text" name="roIsActive" value="@Model.IsActive" class="detailDisplay form-control" readonly />
                    <div class="editForm">
                        <div class="checkbox">
                            @Html.EditorFor(model => model.IsActive)
                            @Html.ValidationMessageFor(model => model.IsActive, "", new { @class = "text-danger" })
                        </div>
                    </div>
                </div>
            </div>
            <div class="form-group">

                @Html.LabelFor(model => model.DateAdded, htmlAttributes: new { @class = "control-label col-md-2" })

                <div class="col-md-10">
                    <input type="text" name="roDateAdded" value="@Model.DateAdded" class="detailDisplay form-control" readonly />
                    <div class="editForm">
                        @Html.EditorFor(model => model.DateAdded, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.DateAdded, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>
            <div class="form-group editForm">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Save" class="submitBtn btn btn-info" />
                </div>
            </div>}

        <div>
            <a href="@Url.Action("Index")" class="btn btn-info">Back to List</a>
            <span id="showEdit" class="detailDisplay btn btn-warning">Edit Record</span>
            <span id="showDetails" class="editForm btn btn-success">View Details</span>
        </div>
    </div>
    </section>

        @section Scripts {
            <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.17.0/jquery.validate.min.js"></script>
            <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validation-unobtrusive/3.2.10/jquery.validate.unobtrusive.min.js"></script>
            <script>
                $(".editForm").hide();
                $(".submitBtn").css('visibility', 'hidden');
                $("#showEdit").click(function () {
                    $(".editForm").show();
                    $(".detailDisplay").hide();
                    $(".submitBtn").css('visibility', 'visible');
                });
                $("#showDetails").click(function () {
                    $(".editForm").hide();
                    $(".detailDisplay").show();
                    $(".submitBtn").css('visibility', 'hidden');
                });
            </script>
        }

FSDP_PrefFut/FSDP_PrefFut/_archive/Views/StudentDocs/Index.cshtml
@model IEnumerable<Data.StudentDoc>
    @using Data

@{
}

<section class="py-5">
    <div class="container">
        <h1>@ViewBag.Title List</h1>

        @*<h2>@ViewBag.Title List</h2>*@

        <p>
            <a href="@Url.Action("Create")" class="btn btn-success"><i class="fas fa-plus"></i> Create</a>
        </p>
        <table class="table">
            <thead>
                <tr>
                    <th>
                        @Html.DisplayNameFor(model => model.DocName)
                    </th>
                    <th>
                            @Html.DisplayNameFor(model => model.StudentID)
                        </th>
                    <th>
                        @Html.DisplayNameFor(model => model.StudentPhoto)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.SpecialNotes)
                    </th>
                    @*<th>
                            @Html.DisplayNameFor(model => model.IsActive)
                        </th>*@
                    <th>
                        @Html.DisplayNameFor(model => model.DateAdded)
                    </th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>
                            @*@Html.DisplayFor(modelItem => item.DocName)*@
                            <a href="@Url.Content("~/Content/images/" + @item.DocName)" target="_blank" alt="@item.DocName">Click To View Document</a>

                        </td>
                     <td>

        @foreach (UserDetail user in ViewBag.userDeets)
        {
        if (item.StudentID == user.UserID)
        {
        <p>@user.FirstName @user.LastName</p>
        }
        }
                                    @*@Html.DisplayFor(modelItem => item.StudentID)
                                    @User.Identity.Name*@
                                </td>

                        <td>
                            @*@Html.DisplayFor(modelItem => item.StudentPhoto)*@
                            <img src="~/Content/images/@item.StudentPhoto" alt="@item.StudentPhoto" title="Photo" style="max-height: 100px; max-width: 100px" />

                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.SpecialNotes)
                        </td>
                        @*<td>
                                @Html.DisplayFor(modelItem => item.IsActive)
                            </td>*@
                        <td>
                            @*@Html.DisplayFor(modelItem => item.DateAdded)*@
                            @item.DateAdded.ToShortDateString()

                        </td>
                        <td class="text-right">
                            <a href="@Url.Action("Edit", new { id = item.StudentDocID })" class="btn btn-warning"><i class="fa fa-info-circle"></i> &nbsp;&nbsp;Details/Edit</a>
                            <a href="@Url.Action("Delete", new { @id=item.StudentDocID })" onclick="return confirm('Are you sure you want to delete item @item.StudentDocID');" class="btn btn-danger"><i class='fa fa-times'></i> &nbsp;&nbsp;Delete</a>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</section>